
name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  

jobs:
  compile:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn compile
  
  security-check:
      runs-on: self-hosted
      needs: compile
      steps:
       - uses: actions/checkout@v4
       - name: Trivy Installation
         run: |
           # Install required packages
            sudo apt-get update
            sudo apt-get install -y wget apt-transport-https gnupg lsb-release

            # Add the GPG key for Trivy
            wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null

            # Add the Trivy repository using the new Signed-By method
            echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/trivy.list > /dev/null

            # Update the package list and install Trivy
            sudo apt-get update
            sudo apt-get install -y trivy
    
       - name: Trivy fs scan
         run: trivy fs --format table -o fs-report.json .
       
       - name: gitleaks Installation
         run: sudo apt install gitleaks -y

       - name: Gitleaks code scan
         run: gitleaks detect source . -r gitleaks-report.json -f json
  Test:
    runs-on: self-hosted
    needs: security-check
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Unit test cases
      run: mvn test    

  
